name: ddpm
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10.0
  - pytorch=2.4.1
  - torchvision=0.19.1
  - matplotlib=3.9.0
  - datasets=4.0.0
  - tqdm=4.66.4
  - numpy=1.24.3
  - scipy=1.14.0
  - einops=0.8.1