name: JitLDM
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jittor=1.3.4.16
  - matplotlib=3.10.1
  - numpy=1.23.0
  - omegaconf=2.2.2
  - pillow=9.2.0
  - requests=2.32.3
  - pytorch=2.1.2
  - torchvision=0.16.2
  - cudatoolkit=11.8
  - tqdm=4.64.0
  - pip